#!/usr/bin/env python2 
import pandas as pd
import matplotlib.pyplot as plt
import os

list_countries=['Afghanistan', 'Iraq', 'Somalia', 'Philippines']
list_categories=['PV.EST', 'RL.EST', 'CC.EST']

df_WGI = pd.read_csv("El_paso.csv")
list(df_WGI)
df_WGI['incident_description'].unique()
list_countries=['Afghanistan', 'Iraq', 'Somalia', 'Philippines']
list_categories=['PV.EST', 'RL.EST', 'CC.EST']
df_countries = df_WGI.loc[df_WGI['Country Name'].isin(list_countries)]
df_indicators = df_countries.loc[df_countries['Indicator Code'].isin(list_categories)]
df_indicators.to_csv(filename you want)

def make_graph(indicator

plt.plot(year_list, df_c_final, label="Corruption")
plt.plot(year_list, df_ps_final, label="Pol Stability")
plt.plot(year_list, df_rl_final, label="Rule Law")
plt.legend()
    filename='/Users/hist-aca2585/Desktop/Aaron-six_{}'.format(country)
    plt.savefig(filename)
    plt.close()
